version: "3.8"

services:
  app:
    build: .
    container_name: currency-exchange-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - PORT=${PORT}
